### ISSUE TITLE
Align behaviour of textual content and 'application' content

### ISSUE THREAD

**Issue by jonkoops** [Amsterdam/amsterdam-styled-components#727]
In the design system there is a non-documented distinction of elements such as links, paragraphs, headers, etc. used in the context of an article or 'textual content' and application context.

For example a link used on an article page has a font-size of 18px, line-height of 22px and when visited is coloured purple. However in the application context the link should always have a font-size of 16px, a line-height of 20px and does not change colour.

Right now all these elements act as textual content, this will have to be changed so that all components act as application content by default and only revert to the textual content behaviour when used inside a `TextualContent` component.

**Todo**
- [ ] Align with the Design System team about behaviour and proposed solution
- [ ] Align with the developers about behaviour and proposed solution
- [ ] Use application styles by default and introduce a `TextualContent` component

**Comment by chrisvanmook** [comment]
Wait for this is resolved https://trello.com/c/jnsiHGpu/351-textual-content-bespreken
We might discard this

**Comment by jonkoops** [comment]
The decision has been made to use the font-sizes on the largest media query by default ([as specified by the DS](https://designsystem.amsterdam.nl/7awj1hc9f/p/632a76-typography/t/a172))
